apiVersion: apps/v1
kind: Deployment
metadata:
  name: flexcub-testing-dep
  namespace: flexcub-testing
  labels:
    app: flexcub-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flexcub-test
  template:
    metadata:
      labels:
        app: flexcub-test
    spec:
      containers:
        - name: flexcub-test
          image: ajiqbrainx/newapp:1
          ports:
            - containerPort: 80